### PR TITLE
DELETION IN A SORTED  ARRAY

### PR DESCRIPTION
**Pull request by Merlin-A**

### CODE REVIEW

**Comment by Merlin-A** [comment]
Hey Thanks for accepting my PR
Can you please add a hacktoberfest-accepted label on it 
Thanks

**Comment by ShivamDev001** [comment]
Now? @Merlin-A

**Review by ShivamDev001 — COMMENTED** [review]
Verified

**Comment by Merlin-A** [comment]
Thanks a lot!

**Comment by ShivamDev001** [comment]
@Merlin-A Just wanted to be clear, is there any other label to assign?

**Comment by Merlin-A** [comment]
I don't think so, Thanks a ton

**Pull request merged**
